title: Jason Papale <br>Data Scientist # your name (or website title) here
logo: "images/Portrait.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, and thank you for visiting my portfolio. My name is Jason Papale, and since my transition out of the military in 2018, I have continued to 
  work to improve my level of knowledge and proficiency in the field of data science. 
  In this portfolio, I have included some of the more substantial projects I have worked on as part of that journey, most of which I completed as part of 
  the UC Berkeley Master of Information and Data Science (MIDS) program. Beyond those projects, I have also included
  a project which mirrors some of the attrition modeling work I was engaged in while employed at USAA, 
  as well as the capstone project from my MBA at Mississippi State University. Please feel free to reach out and/or learn more about my background
  by visiting my <a href="https://www.linkedin.com/in/jason-papale">LinkedIn</a> profile or checking out my 
  <a href="https://drive.google.com/file/d/1XGBR5bOfM1cgLO8-WcyxK8j_IzWQb1ns/view?usp=sharing">resume</a>.
  <br>
  
github: is_project_page:false
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
