title: Jason Papale # your name (or website title) here
logo: "images/Portrait.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is my first description.  I think it take a minute for things to update on Github.
  <br>
  <br>
  Second description
  <br>
  <br>
  <a href="https://www.linkedin.com/in/jason-papale-97912b108">View My LinkedIn Profile</a> 

github:
is\_project\_page:false
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
