title: Jason Papale # your name (or website title) here
logo: "images/Portrait.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Thanks for visiting my porftolio! My name is Jason Papale, and I currently work as a Lead Decision Science Analyst at USAA. 
  Since my transition out of the military in 2018, I have continued to work to improve my level of knowledge and proficiency in the field of data science. 
  In this portfolio, I have included some of the more substantial projects I have worked on as part of that journey, most of which I completed as part of 
  the UC Berkeley Master of Information and Data Science (MIDS) program I recently completed. Outside of the MIDS-related projects, however, I have also included
  a project which mirrors some of the attrition modeling work I have been working on at USAA for a while, 
  as well as my captone project from the MBA I completed at Mississippi State University in 2017.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/jason-papale-97912b108">View My LinkedIn Profile</a> 

github: is_project_page:false
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
