title: Jason Papale # your name (or website title) here
logo: "images/Professional_Portrait.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
    This is my first description
  
  Second description 
  <br>This is my second description<br>
  <a href="https://www.linkedin.com/in/jason-papale-97912b108">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
